-- G01 provenance-first evidence store. IDs are generated by the application so
-- this schema needs no Postgres extensions.

CREATE TABLE sources (
    source_id TEXT PRIMARY KEY,
    source_type TEXT NOT NULL CHECK (source_type IN ('JOBS', 'GITHUB', 'TECHNICAL_WRITING', 'DISCOVERY')),
    name TEXT NOT NULL CHECK (length(trim(name)) > 0),
    canonical_root TEXT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE source_items (
    source_item_id TEXT PRIMARY KEY,
    source_id TEXT NOT NULL REFERENCES sources(source_id),
    native_id TEXT,
    canonical_url TEXT NOT NULL CHECK (length(trim(canonical_url)) > 0),
    title TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (source_id, native_id)
);

-- A provider-native ID is the stronger identity. URL-only items remain unique,
-- while two distinct native items may legitimately share a normalized URL.
CREATE UNIQUE INDEX source_items_source_url_without_native_uq
    ON source_items (source_id, canonical_url)
    WHERE native_id IS NULL;

CREATE TABLE evidence_versions (
    evidence_id TEXT PRIMARY KEY,
    source_item_id TEXT NOT NULL REFERENCES source_items(source_item_id),
    content_hash TEXT NOT NULL CHECK (content_hash ~ '^[0-9a-f]{64}$'),
    retrieved_at TIMESTAMPTZ NOT NULL,
    published_at TIMESTAMPTZ,
    raw_content TEXT,
    snapshot_ref TEXT,
    schema_version INTEGER NOT NULL CHECK (schema_version = 1),
    previous_evidence_id TEXT REFERENCES evidence_versions(evidence_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (raw_content IS NOT NULL OR (snapshot_ref IS NOT NULL AND length(trim(snapshot_ref)) > 0)),
    UNIQUE (source_item_id, content_hash)
);

CREATE TABLE retrievals (
    retrieval_id TEXT PRIMARY KEY,
    evidence_id TEXT NOT NULL REFERENCES evidence_versions(evidence_id),
    retrieved_at TIMESTAMPTZ NOT NULL,
    outcome TEXT NOT NULL CHECK (outcome IN ('SUCCESS', 'FAILED_TRANSIENT', 'FAILED_PERMANENT', 'SKIPPED')),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE provenance_edges (
    edge_id TEXT PRIMARY KEY,
    relationship TEXT NOT NULL CHECK (relationship IN ('DISCOVERED_THROUGH', 'VERSION_OF', 'CONTENT_EQUIVALENT')),
    from_source_item_id TEXT REFERENCES source_items(source_item_id),
    to_source_item_id TEXT REFERENCES source_items(source_item_id),
    from_evidence_id TEXT REFERENCES evidence_versions(evidence_id),
    to_evidence_id TEXT REFERENCES evidence_versions(evidence_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (
        (relationship IN ('DISCOVERED_THROUGH', 'CONTENT_EQUIVALENT')
         AND from_source_item_id IS NOT NULL AND to_source_item_id IS NOT NULL
         AND from_evidence_id IS NULL AND to_evidence_id IS NULL)
        OR
        (relationship = 'VERSION_OF'
         AND from_source_item_id IS NULL AND to_source_item_id IS NULL
         AND from_evidence_id IS NOT NULL AND to_evidence_id IS NOT NULL)
    ),
    UNIQUE (relationship, from_source_item_id, to_source_item_id, from_evidence_id, to_evidence_id)
);

CREATE INDEX source_items_source_id_idx ON source_items (source_id);
CREATE INDEX evidence_versions_published_at_idx ON evidence_versions (published_at);
CREATE INDEX evidence_versions_retrieved_at_idx ON evidence_versions (retrieved_at);
CREATE INDEX retrievals_evidence_id_idx ON retrievals (evidence_id);

-- PostgreSQL treats NULLs as distinct in a regular UNIQUE constraint. This
-- expression index makes the typed edge identity idempotent for both source
-- item edges and evidence version edges.
CREATE UNIQUE INDEX provenance_edges_identity_uq
    ON provenance_edges (
        relationship,
        COALESCE(from_source_item_id, ''),
        COALESCE(to_source_item_id, ''),
        COALESCE(from_evidence_id, ''),
        COALESCE(to_evidence_id, '')
    );
